<?php ?>

<div class="popular_category_homepage">
    <div class="popular_content_wrapper">
        <span class="popular_heading">Популярные категории</span>
        <div class="popular_category_items">

            <a href="#" class="popular_one_item">
                <div class="one_item_imageWrapper">

                </div>
                <div class="one_item_text">

                </div>
            </a>

            <a href="#" class="popular_one_item">
                <div class="one_item_imageWrapper">

                </div>
                <div class="one_item_text">

                </div>
            </a>

            <a href="#" class="popular_one_item">
                <div class="one_item_imageWrapper">

                </div>
                <div class="one_item_text">

                </div>
            </a>

        </div>
    </div>


</div>
